const fs = require('fs');

const existingStations = JSON.parse(fs.readFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', 'utf8'));
const existingCodes = new Set(existingStations.map(s => s.stationCode));

const newStationsRaw = [
    { code: "DMM", name: "Dharmavaram", platforms: 5 },
    { code: "NS", name: "Narasapur", platforms: 3 },
    { code: "BDCR", name: "Bhadrachalam Rd.", platforms: 3 },
    { code: "MALM", name: "Mantralayam Rd.", platforms: 3 },
    { code: "GDV", name: "Gudivada", platforms: 3 },
    { code: "MABD", name: "Mahbubabad", platforms: 3 },
    { code: "BMT", name: "Begumpet", platforms: 2 },
    { code: "NDL", name: "Nandyal", platforms: 3 },
    { code: "TDU", name: "Tandur", platforms: 2 },
    { code: "CTO", name: "Chittoor", platforms: 2 },
    { code: "VKB", name: "Vikarabad", platforms: 3 },
    { code: "RAL", name: "Repalli", platforms: 1 },
    { code: "KGP", name: "Kharagpur", platforms: 12 },
    { code: "ROU", name: "Rourkela", platforms: 5 },
    { code: "HTE", name: "Hatia", platforms: 3 },
    { code: "SHM", name: "Shalimar", platforms: 3 },
    { code: "JSG", name: "Jharsuguda", platforms: 5 },
    { code: "BKSC", name: "Bokaro Steel City", platforms: 3 },
    { code: "BLS", name: "Balasore", platforms: 4 },
    { code: "CKP", name: "Chakradharpur", platforms: 3 },
    { code: "PRR", name: "Purulia Jn.", platforms: 4 },
    { code: "DGHA", name: "Digha", platforms: 3 },
    { code: "BQA", name: "Bankura Jn.", platforms: 3 },
    { code: "MDN", name: "Midnapur", platforms: 3 },
    { code: "ADRA", name: "Adra", platforms: 4 },
    { code: "JGM", name: "Jhargram", platforms: 3 },
    { code: "DURG", name: "Durg", platforms: 5 },
    { code: "G", name: "Gondia", platforms: 7 },
    { code: "RIG", name: "Raigharh", platforms: 3 },
    { code: "CPH", name: "Champa Jn", platforms: 3 },
    { code: "APR", name: "Anuppur", platforms: 4 },
    { code: "RJN", name: "Rajnandgaon", platforms: 3 },
    { code: "SDL", name: "Shahdol", platforms: 3 },
    { code: "BYT", name: "Bhatapara", platforms: 2 },
    { code: "KRBA", name: "Korba", platforms: 3 },
    { code: "BPHB", name: "Bhilai Power House", platforms: 2 },
    { code: "ABKP", name: "Ambikapur", platforms: 2 },
    { code: "ITR", name: "Itwari", platforms: 5 },
    { code: "DGG", name: "Dongargadh", platforms: 3 },
    { code: "UBL", name: "Hubli Junction", platforms: 8 },
    { code: "KJM", name: "Krishnarajapuram", platforms: 4 },
    { code: "BAY", name: "Bellary Jn.", platforms: 4 },
    { code: "DVG", name: "Davangere", platforms: 2 },
    { code: "BWT", name: "Bangarapet", platforms: 6 },
    { code: "MYA", name: "Mandya", platforms: 2 },
    { code: "HPT", name: "Hospet Jn.", platforms: 3 },
    { code: "KGI", name: "Kengeri", platforms: 4 },
    { code: "BJP", name: "Bijapur", platforms: 3 },
    { code: "SSPN", name: "Srisatyasaiprashanthinilayam", platforms: 2 },
    { code: "SMET", name: "Shimoga Tn.", platforms: 3 },
    { code: "GDG", name: "Gadag Jn.", platforms: 3 },
    { code: "ASK", name: "Arsikere", platforms: 3 },
    { code: "YNK", name: "Yelahanka", platforms: 4 },
    { code: "HSRA", name: "Hosur", platforms: 3 },
    { code: "TK", name: "Tumkur", platforms: 3 },
    { code: "MLO", name: "Malur", platforms: 2 },
    { code: "CPT", name: "Channapatna", platforms: 2 },
    { code: "RMGM", name: "Ramanagaram", platforms: 2 },
    { code: "WFD", name: "Whitefield", platforms: 4 },
    { code: "NTW", name: "Nanjangud Tn", platforms: 2 },
    { code: "KPN", name: "Kuppam", platforms: 2 },
    { code: "UJN", name: "Ujjain", platforms: 8 },
    { code: "NVS", name: "Navsari", platforms: 3 },
    { code: "RJT", name: "Rajkot", platforms: 5 },
    { code: "VAPI", name: "Vapi", platforms: 3 },
    { code: "JAM", name: "Jamnagar", platforms: 3 },
    { code: "BH", name: "Bharuch Jn.", platforms: 6 },
    { code: "GIMB", name: "Gandhidham", platforms: 3 },
    { code: "BHUJ", name: "Bhuj", platforms: 3 },
    { code: "ANND", name: "Anand", platforms: 6 },
    { code: "COR", name: "Chittorgarh", platforms: 5 },
    { code: "AKV", name: "Ankleshwar", platforms: 4 },
    { code: "ND", name: "Nadiad", platforms: 4 },
    { code: "BIM", name: "Bilimora", platforms: 3 },
    { code: "VRL", name: "Veraval", platforms: 3 },
    { code: "BVC", name: "Bhavnagar", platforms: 3 },
    { code: "DWK", name: "Dwarka", platforms: 2 },
    { code: "DHD", name: "Dahod", platforms: 3 },
    { code: "NAD", name: "Nagda", platforms: 5 },
    { code: "SUNR", name: "Surendranagar", platforms: 3 },
    { code: "DWX", name: "Dewas", platforms: 2 },
    { code: "JND", name: "Junagarh", platforms: 3 },
    { code: "WKR", name: "Wankaner", platforms: 4 },
    { code: "VG", name: "Viramgam", platforms: 3 },
    { code: "SIOB", name: "Samakhiali", platforms: 3 },
    { code: "NMH", name: "Nimach", platforms: 3 },
    { code: "KSB", name: "Kosamba", platforms: 3 },
    { code: "MHD", name: "Mahemadabad & Kheda Road", platforms: 3 },
    { code: "BTD", name: "Botad", platforms: 3 },
    { code: "MYG", name: "Miyagam Karjan Jn.", platforms: 3 },
    { code: "UBR", name: "Umbergaon", platforms: 3 },
    { code: "KIM", name: "Kim", platforms: 3 },
    { code: "VR", name: "Virar", platforms: 8 },
    { code: "BYR", name: "Bhayandar", platforms: 6 },
    { code: "CCG", name: "Churchgate", platforms: 4 },
    { code: "BSR", name: "Vasai Road", platforms: 8 },
    { code: "NSP", name: "Nallasopara", platforms: 4 },
    { code: "MDD", name: "Malad", platforms: 4 },
    { code: "GMN", name: "Goregaon", platforms: 7 },
    { code: "VTN", name: "Vaitarana", platforms: 2 },
    { code: "KILE", name: "Kandivali", platforms: 4 },
    { code: "VLP", name: "Vile Parley", platforms: 2 },
    { code: "BOR", name: "Boisar", platforms: 3 },
    { code: "MIRA", name: "Mira Road", platforms: 4 },
    { code: "STC", name: "Santacruz", platforms: 4 },
    { code: "JOS", name: "Jogeshwari", platforms: 4 },
    { code: "PLG", name: "Palghar", platforms: 3 },
    { code: "DIC", name: "Dahisar", platforms: 4 },
    { code: "MM", name: "Mahim", platforms: 6 },
    { code: "KHAR", name: "Khar Road", platforms: 4 },
    { code: "GTR", name: "Grant Road", platforms: 4 },
    { code: "DRD", name: "Dahanu Raod", platforms: 3 },
    { code: "EPR", name: "Elphinstone Road", platforms: 2 },
    { code: "CYR", name: "Charni Road", platforms: 4 },
    { code: "STA", name: "Satna", platforms: 3 },
    { code: "KTE", name: "Katni", platforms: 5 },
    { code: "REWA", name: "Rewa", platforms: 2 },
    { code: "SWM", name: "Sawaimadhopur", platforms: 4 },
    { code: "SGO", name: "Saugor", platforms: 2 },
    { code: "BINA", name: "Bina", platforms: 5 },
    { code: "BTE", name: "Bharatpur", platforms: 3 },
    { code: "MYR", name: "Maihar", platforms: 3 },
    { code: "DMO", name: "Damoh", platforms: 3 },
    { code: "GUNA", name: "Guna", platforms: 3 },
    { code: "PPI", name: "Pipariya", platforms: 2 },
    { code: "GGC", name: "Gangapur City", platforms: 3 },
    { code: "BHS", name: "Vidisha", platforms: 4 },
    { code: "HBD", name: "Hoshangabad", platforms: 3 },
    { code: "NU", name: "Narshinghpur", platforms: 2 },
    { code: "HAN", name: "Hindaun City", platforms: 3 },
    { code: "BAQ", name: "Ganjbasoda", platforms: 2 },
    { code: "DKNT", name: "Dakaniya Talav", platforms: 2 },
    { code: "PGMD", name: "Pragati Maidan", platforms: 2 },
    { code: "DBSI", name: "Daya Basti", platforms: 2 },
    { code: "KRTN", name: "Kirti Nagar", platforms: 4 },
    { code: "NRVR", name: "Naraina Vihar", platforms: 2 },
    { code: "DLPI", name: "Delhi Inderpuri", platforms: 2 },
    { code: "BRSQ", name: "Brar Square", platforms: 2 },
    { code: "SDPR", name: "Sardar Patel Marg", platforms: 2 },
    { code: "SOJ", name: "Sarojini Nagar", platforms: 2 },
    { code: "LDCY", name: "Lodhi Colony", platforms: 2 },
    { code: "SWNR", name: "Sewa Nagar", platforms: 2 },
    { code: "PZA", name: "PALAVANTANGAL", platforms: 2 },
    { code: "AVD", name: "AVADI", platforms: 4 },
    { code: "BZN", name: "BAGNAN", platforms: 3 },
    { code: "PKU", name: "PANSKURA", platforms: 3 },
    { code: "MCA", name: "MECHEDA", platforms: 3 },
    { code: "VLCY", name: "Velachery", platforms: 3 },
    { code: "PRGD", name: "Perungudi", platforms: 2 },
    { code: "TRMN", name: "Taramani", platforms: 2 },
    { code: "TYMR", name: "Thiruvanmiyur", platforms: 2 },
    { code: "INDR", name: "Indira Nagar", platforms: 2 },
    { code: "KTBR", name: "Kasturba Nagar", platforms: 2 },
    { code: "KTPM", name: "Kotturpuram", platforms: 2 },
    { code: "GWGR", name: "Greenways Road", platforms: 2 },
    { code: "MNDY", name: "Mandaveli", platforms: 2 },
    { code: "MTMY", name: "Thirumayilai", platforms: 2 },
    { code: "MLHS", name: "Light House", platforms: 2 },
    { code: "MTCN", name: "Thiruvallikeni", platforms: 2 },
    { code: "MCPK", name: "Chepauk", platforms: 2 },
    { code: "MCPT", name: "Chintadripet", platforms: 2 },
    { code: "MPKT", name: "Chennai Park Town", platforms: 2 },
    { code: "GDY", name: "Guindy", platforms: 4 },
    { code: "SP", name: "Saidapet", platforms: 4 },
    { code: "MKK", name: "Kodambakkam", platforms: 4 },
    { code: "NBK", name: "Nungambakkam", platforms: 4 },
    { code: "MSC", name: "Chetput", platforms: 2 },
    { code: "PEW", name: "Perambur Loco Works", platforms: 2 },
    { code: "PCW", name: "Perambur Carriage Works", platforms: 2 },
    { code: "VJM", name: "Vyasarpadi Jeeva", platforms: 2 },
    { code: "TNP", name: "Tondiarpet", platforms: 2 },
    { code: "KOK", name: "Korukkupet", platforms: 4 },
    { code: "MPK", name: "Chennai Park", platforms: 4 },
    { code: "MSF", name: "Chennai Fort", platforms: 4 },
    { code: "WST", name: "Washermanpet", platforms: 4 },
    { code: "BBQ", name: "Basin Bridge", platforms: 6 },
    { code: "RPM", name: "Royapuram", platforms: 2 },
    { code: "MMCC", name: "Moore Market Complex", platforms: 5 },
    { code: "MSB", name: "Chennai Beach", platforms: 8 },
    { code: "SSP", name: "Santoshpur", platforms: 2 },
    { code: "TLG", name: "Tollyganj", platforms: 2 },
    { code: "BGJT", name: "Baghajatin", platforms: 2 },
    { code: "BRJ", name: "Brace Bridge", platforms: 2 },
    { code: "DDC", name: "Dum Dum Cant", platforms: 3 },
    { code: "BLN", name: "Ballygunge", platforms: 4 },
    { code: "DHK", name: "Dhakuria", platforms: 2 },
    { code: "EDG", name: "Eden Garden", platforms: 2 },
    { code: "BEQ", name: "Belur", platforms: 2 },
    { code: "TPKR", name: "Tikiapara", platforms: 2 },
    { code: "LLH", name: "Liluah", platforms: 4 },
    { code: "BBT", name: "Birati", platforms: 2 },
    { code: "MJT", name: "Majerhat", platforms: 4 },
    { code: "KIRP", name: "Khidirpur", platforms: 2 },
    { code: "PPGT", name: "Princep Ghat", platforms: 2 },
    { code: "AGP", name: "Agarpara", platforms: 2 },
    { code: "SRC", name: "Santragachi Junction", platforms: 6 },
    { code: "VVH", name: "Vidyavihar", platforms: 2 },
    { code: "TKNG", name: "Tilak nagar", platforms: 2 },
    { code: "SVE", name: "Sewri", platforms: 2 },
    { code: "SNRD", name: "Sandhurst Road", platforms: 4 },
    { code: "RRD", name: "Reay Road", platforms: 2 },
    { code: "MRU", name: "Matunga Road", platforms: 2 },
    { code: "MTN", name: "Matunga", platforms: 4 },
    { code: "MEL", name: "Marine Lines", platforms: 4 },
    { code: "MSD", name: "Bombay Masjid", platforms: 4 },
    { code: "MX", name: "Mahalaxmi", platforms: 4 },
    { code: "DKRD", name: "Dockyard Road", platforms: 2 },
    { code: "CRD", name: "Currey Road", platforms: 2 },
    { code: "CTGN", name: "Cotton Green", platforms: 2 },
    { code: "CHF", name: "Chunabhatti", platforms: 2 },
    { code: "CHG", name: "Chinchpokli", platforms: 2 },
    { code: "BAP", name: "CBD Belapur", platforms: 4 }
];

newStationsRaw.forEach(s => {
    if (!existingCodes.has(s.code)) {
        existingStations.push({
            stationCode: s.code,
            stationName: s.name,
            platforms: s.platforms,
            location: { lat: 0, lng: 0 } // Dummy coordinates
        });
    }
});

fs.writeFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', JSON.stringify(existingStations, null, 2));
console.log(`Added ${existingStations.length - existingCodes.size} new stations.`);
