const fs = require('fs');

const existingStations = JSON.parse(fs.readFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', 'utf8'));
const existingCodes = new Set(existingStations.map(s => s.stationCode));

const newStationsRaw = [
    { code: "NBD", name: "Najibabad", platforms: 3 },
    { code: "ABS", name: "Abhohar Jn", platforms: 2 },
    { code: "SBB", name: "Sahibabad", platforms: 5 },
    { code: "BGZ", name: "Bahdurgrah", platforms: 3 },
    { code: "NNO", name: "Nangloi", platforms: 2 },
    { code: "NUR", name: "Narela", platforms: 2 },
    { code: "TKD", name: "Tughlakabad", platforms: 3 },
    { code: "MDNR", name: "Modinagar", platforms: 2 },
    { code: "NOLI", name: "Noli", platforms: 2 },
    { code: "GNU", name: "Ganaur", platforms: 2 },
    { code: "FDN", name: "Faridabad New Town", platforms: 3 },
    { code: "PTRD", name: "Pataudi road", platforms: 2 },
    { code: "BTU", name: "Braut", platforms: 2 },
    { code: "AMRO", name: "Amroha", platforms: 3 },
    { code: "PM", name: "Palam", platforms: 2 },
    { code: "DSB", name: "Delhi sadar bazar", platforms: 2 },
    { code: "JHS", name: "Jhansi", platforms: 8 },
    { code: "MTJ", name: "Mathura", platforms: 9 },
    { code: "AF", name: "Agra Fort", platforms: 5 },
    { code: "ALJN", name: "Aligarh", platforms: 7 },
    { code: "COI", name: "Chheoki", platforms: 3 },
    { code: "MZP", name: "Mirzapur", platforms: 3 },
    { code: "ETW", name: "Etawah", platforms: 5 },
    { code: "TDL", name: "Tundala", platforms: 5 },
    { code: "BNDA", name: "Banda", platforms: 3 },
    { code: "MRA", name: "Morena", platforms: 2 },
    { code: "LAR", name: "Lalitpur", platforms: 3 },
    { code: "CKTD", name: "Chitrakut Dham", platforms: 2 },
    { code: "MBA", name: "Mahoba", platforms: 3 },
    { code: "FTP", name: "Fatehpur", platforms: 3 },
    { code: "RKM", name: "Raja ki Mandi", platforms: 2 },
    { code: "MKP", name: "Manikpur", platforms: 4 },
    { code: "ORAI", name: "Orai", platforms: 2 },
    { code: "KURJ", name: "Khajuraho", platforms: 3 },
    { code: "PHD", name: "Phaphund", platforms: 2 },
    { code: "DAA", name: "Datia", platforms: 2 },
    { code: "DHO", name: "Dholpur Jn.", platforms: 3 },
    { code: "DBA", name: "Dabra", platforms: 2 },
    { code: "DER", name: "Dadri", platforms: 2 },
    { code: "KRJ", name: "Khurja", platforms: 3 },
    { code: "CPR", name: "Chhapra Jn", platforms: 6 },
    { code: "SV", name: "Siwan", platforms: 4 },
    { code: "GD", name: "Gonda Jn", platforms: 5 },
    { code: "MUV", name: "Manduwadih", platforms: 8 },
    { code: "BST", name: "Basti", platforms: 3 },
    { code: "AMH", name: "Azamgrah", platforms: 3 },
    { code: "BUI", name: "Ballia", platforms: 4 },
    { code: "MAU", name: "Mau Jn", platforms: 4 },
    { code: "DEOS", name: "Deoria Sadar", platforms: 3 },
    { code: "KGM", name: "Kathgodam", platforms: 3 },
    { code: "KLD", name: "Khalilabad", platforms: 2 },
    { code: "FBD", name: "Farrukhabad", platforms: 5 },
    { code: "GCT", name: "Ghazipur City", platforms: 3 },
    { code: "RUPC", name: "Rudrapur City", platforms: 2 },
    { code: "BLTR", name: "Belthara Road", platforms: 2 },
    { code: "BNZ", name: "Badshahnagar", platforms: 2 },
    { code: "KSJ", name: "Kasganj Jn.", platforms: 5 },
    { code: "KJN", name: "Kannauj", platforms: 3 },
    { code: "BCY", name: "Varanasi City", platforms: 5 },
    { code: "BTT", name: "Bhatni", platforms: 5 },
    { code: "LKU", name: "Lalkuan Jn.", platforms: 3 },
    { code: "HDW", name: "Haldwani", platforms: 2 },
    { code: "MUR", name: "Mankapur Jn.", platforms: 4 },
    { code: "KPV", name: "Kashipur", platforms: 3 },
    { code: "PBE", name: "Pilibhit Jn.", platforms: 4 },
    { code: "BC", name: "Bareilly City", platforms: 4 },
    { code: "NJP", name: "New Jalpaiguri", platforms: 8 },
    { code: "KIR", name: "Katihar", platforms: 8 },
    { code: "KYQ", name: "Kamakhya", platforms: 4 },
    { code: "DMV", name: "Dimapur", platforms: 2 },
    { code: "KNE", name: "Kishanganj", platforms: 3 },
    { code: "NCB", name: "New Coochbehar", platforms: 5 },
    { code: "NTSK", name: "New Tinsukia", platforms: 3 },
    { code: "DBRT", name: "Dibrugarh Town", platforms: 3 },
    { code: "NBQ", name: "New Bongaigaon", platforms: 6 },
    { code: "RNY", name: "Rangiya Jn.", platforms: 5 },
    { code: "MXN", name: "Mariyani Jn.", platforms: 3 },
    { code: "NOQ", name: "New Alipurduar", platforms: 3 },
    { code: "BOE", name: "Barsoi Jn.", platforms: 3 },
    { code: "DBRG", name: "Dibrugarh", platforms: 5 },
    { code: "SCL", name: "Silchar", platforms: 3 },
    { code: "JBN", name: "Jogbani", platforms: 2 },
    { code: "LMG", name: "Lumding", platforms: 5 },
    { code: "RGJ", name: "Raiganj", platforms: 2 },
    { code: "BPRD", name: "Barpeta Road", platforms: 3 },
    { code: "APDJ", name: "Alipurduar Jn.", platforms: 3 },
    { code: "DQG", name: "Dhupguri", platforms: 2 },
    { code: "KOJ", name: "Kokrajhar", platforms: 2 },
    { code: "SGUJ", name: "Siliguri Jn.", platforms: 5 },
    { code: "PRNA", name: "Purnea", platforms: 3 },
    { code: "ARQ", name: "Araria Court", platforms: 2 },
    { code: "BKN", name: "Bikaner", platforms: 6 },
    { code: "ABR", name: "Abu Road", platforms: 3 },
    { code: "RE", name: "Rewari", platforms: 6 },
    { code: "AWR", name: "Alwar", platforms: 3 },
    { code: "FA", name: "Falna", platforms: 3 },
    { code: "SGNR", name: "Sri Ganga Nagar", platforms: 3 },
    { code: "HSR", name: "Hisar", platforms: 3 },
    { code: "JSM", name: "Jaisalmer", platforms: 3 },
    { code: "BHL", name: "Bhilwara", platforms: 4 },
    { code: "BKI", name: "Bandikui", platforms: 6 },
    { code: "SOG", name: "Suratgarh", platforms: 4 },
    { code: "NGO", name: "Nagaur", platforms: 3 },
    { code: "MJ", name: "Marwar Jn.", platforms: 6 },
    { code: "PMY", name: "Pali Marwar", platforms: 3 },
    { code: "BME", name: "Barmer", platforms: 3 },
    { code: "BGKT", name: "Bhagar Ki Kothi", platforms: 3 },
    { code: "LGH", name: "Lalgarh", platforms: 3 },
    { code: "HMH", name: "Hanumangarh Jn.", platforms: 3 },
    { code: "BNW", name: "Bhiwani", platforms: 3 },
    { code: "MTD", name: "Merta Road", platforms: 4 },
    { code: "DO", name: "Dausa", platforms: 3 },
    { code: "KSG", name: "Kishangarh", platforms: 2 },
    { code: "FL", name: "Phulera", platforms: 5 },
    { code: "DPA", name: "Durgapura", platforms: 2 },
    { code: "BER", name: "Beawar", platforms: 3 },
    { code: "SSA", name: "Sirsa", platforms: 3 },
    { code: "MS", name: "Chennai Egmore", platforms: 11 },
    { code: "TBM", name: "Tambaram", platforms: 8 },
    { code: "CBE", name: "Coimbatore Jn", platforms: 6 },
    { code: "CLT", name: "Kozhikkode", platforms: 4 },
    { code: "KPD", name: "Katpadi", platforms: 5 },
    { code: "TCR", name: "Thrisur", platforms: 4 },
    { code: "CGL", name: "Chengalpattu Jn.", platforms: 8 },
    { code: "AJJ", name: "Arakkonam Jn.", platforms: 8 },
    { code: "TRL", name: "Tiruvallur", platforms: 6 },
    { code: "TPJ", name: "Tiruchchirappalli Jn", platforms: 8 },
    { code: "TEN", name: "Tirunelveli Jn.", platforms: 5 },
    { code: "MAQ", name: "Mangalore Central", platforms: 5 },
    { code: "ED", name: "Erode Jn", platforms: 4 },
    { code: "SA", name: "Salem Jn.", platforms: 6 },
    { code: "CAN", name: "Kannur", platforms: 4 },
    { code: "ERN", name: "Eraniel", platforms: 2 },
    { code: "TUP", name: "Tiruppur", platforms: 2 },
    { code: "AWY", name: "Aluva", platforms: 3 },
    { code: "PGT", name: "Palakkad jn", platforms: 5 },
    { code: "QLN", name: "Kollam Jn", platforms: 6 },
    { code: "KTYM", name: "Kottayam", platforms: 3 },
    { code: "SRR", name: "Shoranur Jn", platforms: 7 },
    { code: "CNGR", name: "Chengannur", platforms: 2 },
    { code: "NCJ", name: "Nagercoil Jn.", platforms: 4 },
    { code: "KYJ", name: "Kayankulam Jn", platforms: 6 },
    { code: "TLY", name: "Thalassery", platforms: 2 },
    { code: "TJ", name: "Thanjavur Jn", platforms: 5 },
    { code: "MAJN", name: "Mangalore Jn.", platforms: 3 },
    { code: "DG", name: "Dindigul Jn", platforms: 5 },
    { code: "RMM", name: "Rameswaram", platforms: 4 },
    { code: "TN", name: "Tutikorin", platforms: 2 },
    { code: "JTJ", name: "Jolarpattai", platforms: 5 },
    { code: "TIR", name: "Tirur", platforms: 3 },
    { code: "VM", name: "Villupuram Jn", platforms: 6 },
    { code: "KCVL", name: "Kochuvalli", platforms: 6 },
    { code: "ALLP", name: "Alppuzha", platforms: 3 },
    { code: "PER", name: "Perambur", platforms: 4 },
    { code: "MBM", name: "Mambalam", platforms: 4 },
    { code: "GI", name: "Guduvancheri", platforms: 2 },
    { code: "PRGL", name: "Perungalathur", platforms: 2 },
    { code: "CAPE", name: "Kanniyakumari", platforms: 3 },
    { code: "BDJ", name: "Vadakara", platforms: 3 },
    { code: "KGQ", name: "Kasargod", platforms: 3 },
    { code: "TRVL", name: "Tiruvalla", platforms: 3 },
    { code: "KMU", name: "Kumbakonam", platforms: 3 },
    { code: "PAY", name: "Payyannur", platforms: 3 },
    { code: "CVP", name: "Kovilpatti", platforms: 3 },
    { code: "VPT", name: "Virudhunagar Jn", platforms: 3 },
    { code: "MV", name: "Mayiladuthurai Jn", platforms: 4 },
    { code: "NGT", name: "Nagappattinam", platforms: 3 },
    { code: "KZE", name: "Kanhangad", platforms: 3 },
    { code: "KRR", name: "Karur Jn.", platforms: 3 },
    { code: "RMD", name: "Ramanathapuram", platforms: 3 },
    { code: "KTU", name: "Kuttipuram", platforms: 3 },
    { code: "MTP", name: "Mettupalaiyam", platforms: 2 },
    { code: "CGY", name: "Changanacheri", platforms: 3 },
    { code: "VAK", name: "Varkalashivagiri", platforms: 3 },
    { code: "TRT", name: "Tiruttani", platforms: 2 },
    { code: "SKL", name: "Singaperumalkoil", platforms: 2 },
    { code: "AFK", name: "Angamali for Kaladi", platforms: 3 },
    { code: "HYB", name: "Hyderabad", platforms: 6 },
    { code: "KCG", name: "Kacheguda", platforms: 5 },
    { code: "NED", name: "Huzur Saheb Nanded", platforms: 4 },
    { code: "RJY", name: "Rajahmundry", platforms: 3 },
    { code: "AWB", name: "Aurangabad", platforms: 3 },
    { code: "RU", name: "Renigunta", platforms: 6 },
    { code: "GNT", name: "Guntur", platforms: 7 },
    { code: "WL", name: "Warangal", platforms: 4 },
    { code: "SLO", name: "Samalkot", platforms: 3 },
    { code: "KZJ", name: "Kazipet Jn", platforms: 3 },
    { code: "OGL", name: "Ongole", platforms: 3 },
    { code: "KMT", name: "Khammam", platforms: 3 },
    { code: "GTL", name: "Guntakal", platforms: 7 },
    { code: "GDR", name: "Gudur", platforms: 3 },
    { code: "CCT", name: "Kakinada Tn.", platforms: 3 },
    { code: "RC", name: "Raichur", platforms: 3 },
    { code: "PBN", name: "Parbhani", platforms: 3 },
    { code: "NSL", name: "Nagarsol", platforms: 2 },
    { code: "TEL", name: "Tenali", platforms: 3 },
    { code: "ATP", name: "Anatpur", platforms: 3 },
    { code: "NZB", name: "Nizamabad", platforms: 3 },
    { code: "YG", name: "Yadgir", platforms: 2 },
    { code: "EE", name: "Eluru", platforms: 3 },
    { code: "BVRT", name: "Bhimavaram Tn.", platforms: 2 },
    { code: "HX", name: "Cuddapah", platforms: 3 },
    { code: "LPI", name: "Lingampalli", platforms: 3 },
    { code: "KRNT", "name": "Kurnool Tn", platforms: 3 },
    { code: "AKP", name: "Anakapalli", platforms: 2 },
    { code: "J", name: "Jalna", platforms: 3 },
    { code: "TDD", name: "Tadepalligudem", platforms: 2 },
    { code: "CLX", name: "Chirala", platforms: 2 },
    { code: "TUNI", name: "Tuni", platforms: 3 },
    { code: "MCI", name: "Manchiryal", platforms: 3 },
    { code: "BIDR", name: "Bidar", platforms: 3 },
    { code: "AD", name: "Adoni", platforms: 3 },
    { code: "COA", name: "Kakinada Port (new)", platforms: 2 },
    { code: "RDM", name: "Ramagundam", platforms: 3 }
];

newStationsRaw.forEach(s => {
    if (!existingCodes.has(s.code)) {
        existingStations.push({
            stationCode: s.code,
            stationName: s.name,
            platforms: s.platforms,
            location: { lat: 0, lng: 0 } // Dummy coordinates
        });
    }
});

fs.writeFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', JSON.stringify(existingStations, null, 2));
console.log(`Added ${existingStations.length - existingCodes.size} new stations.`);
