const fs = require('fs');

const existingStations = JSON.parse(fs.readFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', 'utf8'));
const existingCodes = new Set(existingStations.map(s => s.stationCode));

const newStationsRaw = [
    { code: "SUR", name: "Solapur", platforms: 7 },
    { code: "MMR", name: "Manmad", platforms: 6 },
    { code: "GR", name: "Gulbarga", platforms: 4 },
    { code: "AK", name: "Akola", platforms: 5 },
    { code: "MRJ", name: "Miraj", platforms: 5 },
    { code: "SNSI", name: "Sainagar Shirdi", platforms: 3 },
    { code: "KOP", name: "Kolhapur", platforms: 3 },
    { code: "BD", name: "Badnera", platforms: 4 },
    { code: "KNW", name: "Khandwa", platforms: 5 },
    { code: "KPG", name: "Kopargaon", platforms: 2 },
    { code: "DD", name: "Daund", platforms: 6 },
    { code: "ANG", name: "Ahmednagar", platforms: 2 },
    { code: "WR", name: "Wardha", platforms: 4 },
    { code: "SEG", name: "Shegaon", platforms: 2 },
    { code: "AMI", name: "Amrawati", platforms: 3 },
    { code: "BPQ", name: "Balharshah", platforms: 5 },
    { code: "CD", name: "Chandrapur", platforms: 3 },
    { code: "LUR", name: "Latur", platforms: 3 },
    { code: "BZU", name: "Betul", platforms: 2 },
    { code: "BAU", name: "Burhanpur", platforms: 2 },
    { code: "KWV", name: "Kurduwadi", platforms: 4 },
    { code: "CSN", name: "Chalisgaon", platforms: 3 },
    { code: "MKU", name: "Malkapur", platforms: 2 },
    { code: "SEGM", name: "Sewagram", platforms: 4 },
    { code: "BIRD", name: "Bhiwandi Road", platforms: 2 },
    { code: "WADI", name: "Wadi", platforms: 4 },
    { code: "DI", name: "Dombivali", platforms: 5 },
    { code: "BUD", name: "Badalapur", platforms: 3 },
    { code: "GC", name: "Ghatkopar", platforms: 4 },
    { code: "CLA", name: "Kurla", platforms: 8 },
    { code: "ABH", name: "Ambarnath", platforms: 3 },
    { code: "MNKD", name: "Mankhurd", platforms: 2 },
    { code: "MLND", name: "Mulund", platforms: 4 },
    { code: "MBQ", name: "Mumbra", platforms: 2 },
    { code: "BEPR", name: "Belapur", platforms: 4 },
    { code: "TLA", name: "Titwala", platforms: 3 },
    { code: "BND", name: "Bhandup", platforms: 2 },
    { code: "NEU", name: "Nerul", platforms: 4 },
    { code: "VSH", name: "Vashi", platforms: 4 },
    { code: "KHAG", name: "Kharghar", platforms: 2 },
    { code: "GV", name: "Govandi", platforms: 2 },
    { code: "ULNR", name: "Ulhasnagar", platforms: 2 },
    { code: "VK", name: "Vikhroli", platforms: 2 },
    { code: "KLVA", name: "Kalwa", platforms: 2 },
    { code: "BY", name: "Byculla", platforms: 4 },
    { code: "SIN", name: "Sion", platforms: 2 },
    { code: "AIRL", name: "Aeroli", platforms: 2 },
    { code: "KJT", name: "Karjat", platforms: 3 },
    { code: "CMBR", name: "Chembur", platforms: 2 },
    { code: "GTBN", name: "Guru Teg Bahadur Nagar", platforms: 2 },
    { code: "GNSL", name: "Ghansoli", platforms: 2 },
    { code: "MANR", name: "Mansarovar", platforms: 2 },
    { code: "SNCR", name: "Sanpada", platforms: 2 },
    { code: "KOAA", name: "Kolkata Terminal", platforms: 5 },
    { code: "BGP", name: "Bhagalpur", platforms: 6 },
    { code: "ASN", name: "Asansol", platforms: 7 },
    { code: "BWN", name: "Barddhaman", platforms: 8 },
    { code: "NH", name: "Naihati", platforms: 5 },
    { code: "MLDT", name: "Malda Town", platforms: 6 },
    { code: "JSME", name: "Jasidih", platforms: 5 },
    { code: "DGR", name: "Durgapur", platforms: 5 },
    { code: "JMP", name: "Jamalpur", platforms: 4 },
    { code: "RPH", name: "Rampurhat", platforms: 3 },
    { code: "BDC", name: "Bandel Jn.", platforms: 7 },
    { code: "NFK", name: "New Farakka", platforms: 3 },
    { code: "MDP", name: "Madhupur", platforms: 4 },
    { code: "BHP", name: "Bolpur", platforms: 3 },
    { code: "BPC", name: "Berhampur Court", platforms: 2 },
    { code: "SGG", name: "Sultanganj", platforms: 2 },
    { code: "RNG", name: "Raniganj", platforms: 3 },
    { code: "UDL", name: "Andal", platforms: 6 },
    { code: "KNJ", name: "Krishnanagar City", platforms: 4 },
    { code: "BP", name: "Barrackpur", platforms: 4 },
    { code: "SPR", name: "Srirampur", platforms: 4 },
    { code: "DDJ", name: "Dum Dum Jn.", platforms: 5 },
    { code: "SEP", name: "Sodepur", platforms: 4 },
    { code: "BRP", name: "Baruipur Jn.", platforms: 4 },
    { code: "SRP", name: "Shrirampur", platforms: 4 },
    { code: "RIS", name: "Rishra", platforms: 4 },
    { code: "KOG", name: "Konnagar", platforms: 4 },
    { code: "BT", name: "Barasat Jn.", platforms: 6 },
    { code: "BLH", name: "Belghoria", platforms: 4 },
    { code: "SBGR", name: "Subhasgram", platforms: 2 },
    { code: "SNR", name: "Shyamnagar", platforms: 4 },
    { code: "BNXR", name: "Bidhannagar", platforms: 4 },
    { code: "HB", name: "Habra", platforms: 2 },
    { code: "MMG", name: "Madhyamgram", platforms: 4 },
    { code: "SHE", name: "Sheoraphuli", platforms: 6 },
    { code: "RHA", name: "Ranaghat Jn.", platforms: 6 },
    { code: "KDH", name: "Khardah", platforms: 4 },
    { code: "CDH", name: "Chakdah", platforms: 4 },
    { code: "MFP", name: "Muzaffarpur", platforms: 5 },
    { code: "MGS", name: "Mughalsarai", platforms: 8 },
    { code: "DBG", name: "Darbhanga", platforms: 5 },
    { code: "RJPB", name: "Rajendra Nagar Terminal", platforms: 4 },
    { code: "PPTA", name: "Patliputra", platforms: 3 },
    { code: "SPJ", name: "Samastipur", platforms: 7 },
    { code: "SHC", name: "Saharsa", platforms: 5 },
    { code: "ARA", name: "Ara", platforms: 3 },
    { code: "BXR", name: "Buxar", platforms: 3 },
    { code: "DNR", name: "Danapur", platforms: 6 },
    { code: "BJU", name: "Barauni Jn.", platforms: 9 },
    { code: "HJP", name: "Hajipur", platforms: 5 },
    { code: "KQR", name: "Koderma", platforms: 4 },
    { code: "BMKI", name: "Banmankhi", platforms: 2 },
    { code: "DOS", name: "Dehri On Sone", platforms: 4 },
    { code: "KIUL", name: "Kiul", platforms: 5 },
    { code: "KGG", name: "Khagaria", platforms: 3 },
    { code: "RXL", name: "Raxaul", platforms: 3 },
    { code: "SSM", name: "Sasaram", platforms: 3 },
    { code: "BTH", name: "Bettiah", platforms: 2 },
    { code: "JYG", name: "Jainagar", platforms: 3 },
    { code: "PNME", name: "Parasnath", platforms: 3 },
    { code: "MBI", name: "Madhubani", platforms: 3 },
    { code: "DTO", name: "Daltengunj", platforms: 2 },
    { code: "BKP", name: "Bakhtiyarpur", platforms: 3 },
    { code: "AUBR", name: "Anugrah Narayan Road", platforms: 3 },
    { code: "SGL", name: "Sugauli", platforms: 2 },
    { code: "NKE", name: "Narkatiaganj", platforms: 3 },
    { code: "BGS", name: "Begusarai", platforms: 3 },
    { code: "SKI", name: "Sakari Jn", platforms: 3 },
    { code: "PNC", name: "Patna Sahib", platforms: 2 },
    { code: "SMI", name: "Sitamadhi", platforms: 2 },
    { code: "JMU", name: "Jamui", platforms: 2 },
    { code: "MKA", name: "Mokama", platforms: 4 },
    { code: "JAJ", name: "Jhanja", platforms: 4 },
    { code: "SGRL", name: "Singrauli", platforms: 2 },
    { code: "BBU", name: "Bhabhua Road", platforms: 3 },
    { code: "GHD", name: "Garhwa Road", platforms: 3 },
    { code: "MNE", name: "Mansi Jn.", platforms: 3 },
    { code: "DLN", name: "Dildarnagar", platforms: 2 },
    { code: "BUG", name: "Bagha", platforms: 2 },
    { code: "NNA", name: "Naugachia", platforms: 2 },
    { code: "SEE", name: "Sonepur", platforms: 4 },
    { code: "BRKA", name: "Barkakana", platforms: 3 },
    { code: "JHD", name: "Jahanabad", platforms: 2 },
    { code: "TEA", name: "Taregana", platforms: 2 },
    { code: "FUT", name: "Fatuha", platforms: 2 },
    { code: "BTA", name: "Bihta", platforms: 2 },
    { code: "BARH", name: "Barh", platforms: 2 },
    { code: "PURI", name: "Puri", platforms: 8 },
    { code: "BAM", name: "Brahmapur", platforms: 4 },
    { code: "CTC", name: "Cuttack", platforms: 5 },
    { code: "VZM", name: "Vizianagaram", platforms: 5 },
    { code: "SBP", name: "Sambalpur", platforms: 4 },
    { code: "KUR", name: "Khurda Road", platforms: 7 },
    { code: "CHE", name: "Srikakulam", platforms: 3 },
    { code: "BHC", name: "Bhadrak", platforms: 4 },
    { code: "PSA", name: "Palasa", platforms: 3 },
    { code: "RGDA", name: "Rayagada", platforms: 3 },
    { code: "JJKR", name: "Jajpur-Keonjhar road", platforms: 3 },
    { code: "DVD", name: "Duvvada", platforms: 4 },
    { code: "BLGR", name: "Bolangir", platforms: 2 },
    { code: "TIG", name: "Titlagrah", platforms: 3 },
    { code: "BALU", name: "Balugaon", platforms: 2 },
    { code: "KSNG", name: "Kesinga", platforms: 2 },
    { code: "DLI", name: "Delhi", platforms: 16 },
    { code: "LDH", name: "Ludhiana Jn", platforms: 7 },
    { code: "HW", name: "Haridwar", platforms: 9 },
    { code: "SNP", name: "Sonipat", platforms: 4 },
    { code: "DDN", name: "Dehradun", platforms: 4 },
    { code: "SVDK", name: "Shri Mata Vaisno devi Katra", platforms: 4 },
    { code: "SRE", name: "Saharanpur", platforms: 6 },
    { code: "FD", name: "Faizabad", platforms: 4 },
    { code: "BTI", name: "Bathinda", platforms: 7 },
    { code: "PTKC", name: "Pathankot Jn", platforms: 4 },
    { code: "MTC", name: "Meerut City", platforms: 5 },
    { code: "SLN", name: "Sultanpur", platforms: 3 },
    { code: "JRC", name: "Jalandhar City", platforms: 5 },
    { code: "SPN", name: "Shahjahanpur", platforms: 4 },
    { code: "KLK", name: "Kalka", platforms: 4 },
    { code: "PBH", name: "Pratapgarh", platforms: 3 },
    { code: "SHG", name: "Shahgunj", platforms: 4 },
    { code: "FZR", name: "Firozpur Cantt", platforms: 5 },
    { code: "JNU", name: "Jaunpur", platforms: 5 },
    { code: "ABP", name: "Akbarpur", platforms: 2 },
    { code: "RBL", name: "Raebareli", platforms: 4 },
    { code: "RK", name: "Roorkee", platforms: 3 },
    { code: "ROK", name: "Rohtak", platforms: 3 },
    { code: "HRI", name: "Hardoi", platforms: 3 },
    { code: "MOZ", name: "Muzaffar Nagar", platforms: 3 },
    { code: "PGW", name: "Phagwara Jn.", platforms: 3 },
    { code: "PWL", name: "Palwal", platforms: 4 },
    { code: "RMU", name: "Rampur", platforms: 3 },
    { code: "UHP", name: "Udhampur", platforms: 3 },
    { code: "BOY", name: "Bhadohi", platforms: 2 },
    { code: "RPJ", name: "Raj Pura", platforms: 4 },
    { code: "JNH", name: "Janghai", platforms: 3 },
    { code: "PRG", name: "Paryag", platforms: 2 },
    { code: "PTK", name: "Pathan kot Jn", platforms: 4 },
    { code: "HPU", name: "Hapur", platforms: 3 },
    { code: "ON", name: "Unnao", platforms: 3 },
    { code: "SIR", name: "Sirhind", platforms: 3 },
    { code: "KKDE", name: "Kurukshetra", platforms: 3 },
    { code: "BBK", name: "Barabanki", platforms: 4 },
    { code: "JOP", name: "Jaunpur City", platforms: 3 },
    { code: "PTA", name: "Patiala", platforms: 3 },
    { code: "BVH", name: "Ballabhgrah", platforms: 2 },
    { code: "AY", name: "Ayodhya", platforms: 3 },
    { code: "AME", name: "Amethi", platforms: 2 },
    { code: "CH", name: "Chandausi", platforms: 3 }
];

newStationsRaw.forEach(s => {
    if (!existingCodes.has(s.code)) {
        existingStations.push({
            stationCode: s.code,
            stationName: s.name,
            platforms: s.platforms,
            location: { lat: 0, lng: 0 } // Dummy coordinates
        });
    }
});

fs.writeFileSync('/Users/shubhamgaonkar/Desktop/AntiGravity/backend/data/stations.json', JSON.stringify(existingStations, null, 2));
console.log(`Added ${existingStations.length - existingCodes.size} new stations.`);
